### ISSUE TITLE
data source yandex_resourcemanager_cloud requires folder_id to get cloud_id

### ISSUE THREAD

**Issue by asterix201** [yandex-cloud/terraform-provider-yandex#32]
I'm not sure when it started to be, but today I've faced with next issue: 

I'm trying to get cloud id by its name: 
```
data "yandex_resourcemanager_cloud" "cloud" {
  name = var.cloud_name
}
```

But on plan step I'm receiving an error: 
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.yandex_resourcemanager_cloud.cloud: Refreshing state...

Error: failed to resolve data source cloud by name: cannot determine folder_id: please set 'folder_id' key in this resource or at provider level

  on main.tf line 89, in data "yandex_resourcemanager_cloud" "cloud":
  89: data "yandex_resourcemanager_cloud" "cloud" {
```

I'm not sure, but previously it worked without specifying `folder_id` at any level. 
Because normally I use the next pipeline in my scripts: get cloud id by cloud name -> get folder id by folder name and cloud id.

**Comment by asterix201** [comment]
Sorry, forgot some details :) 

Terraform v0.12.10
+ provider.yandex v0.26.0

And I tested with 
Terraform v0.12.10
+ provider.yandex v0.23.0

And it works fine without errors

**Comment by alexanderKhaustov** [comment]
Thanks for reporting the problem. This bug was indeed introduced starting with provider v0.24.0. We'll fix it in the next version of the provider. In the meantime you might either use an earlier version of the provider or specify folder_id in the provider configuration

**Comment by asterix201** [comment]
@GennadySpb а почему реквесты закрыли?
Непочинено же, насколько я проверял на новых версиях

**Comment by alexanderKhaustov** [comment]
Yep, closed by mistake

**Comment by seukyaso** [comment]
Fixed in plugin verion: 0.29.1

**Comment by asterix201** [comment]
@seukyaso @GennadySpb @alexanderKhaustov 
Tried with version 0.32.0
Still broken...

**Comment by seukyaso** [comment]
Just tested on a simple config (changed real name and id though):

provider "yandex" {
  token = "MY_TOKEN"
}

data "yandex_resourcemanager_cloud" "cloud" {
  name = "MY-CLOUD-NAME"
}

output "my_cloud_id" {
  value = data.yandex_resourcemanager_cloud.cloud.cloud_id
}

Seems working to me, please see the output below.
BTW, v 0.32.0 is not yet released, did you build it yourself?

```
seukyaso@seuvm:~/work/testterraform/test_cloud$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "yandex" (terraform-providers/yandex) 0.31.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.yandex: version = "~> 0.31"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
seukyaso@seuvm:~/work/testterraform/test_cloud$ terraform refresh
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.

data.yandex_resourcemanager_cloud.cloud: Refreshing state...

Outputs:

my_cloud_id = MY-CLOUD-ID
```

**Comment by seukyaso** [comment]
Ah, found the problem now, with resolving folder by name =( We will make a fix in a nearest future.

**Comment by asterix201** [comment]
@seukyaso fixed on the latest release, thank you!
